# Generated by Django 3.1.4 on 2020-12-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201220_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='logged_in_before',
            field=models.BooleanField(default=False),
        ),
    ]
