# Generated by Django 3.1.4 on 2020-12-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile_logged_in_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='custom_id',
            field=models.CharField(default='0cus_rcus_kcus_dcus_wcus_ecus_8cus_tcus_6cus_hcus_zcus_rcus_tcus_ucus_zcus_mcus_rcus_6cus_5cus_e', max_length=20),
        ),
    ]
