# Generated by Django 3.1.4 on 2020-12-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='custom_id',
            field=models.CharField(default='yj0heqh1l0nn6wfuamo1', max_length=20),
        ),
    ]
