# Generated by Django 3.1.4 on 2020-12-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201220_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='custom_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='customer_id',
            field=models.CharField(default='h2rzfhkhdkmj8l5xf4st', max_length=20),
        ),
    ]
